// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.865
package layout

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/labstack/echo/v4"
	"gostart-crm/internal/catalog/category"
	"gostart-crm/internal/template/component/sidebar"
)

type MainProps struct {
	CategoryName string
	CategoryTree category.Category
}

func categoryTreeToSidebarGroups(tree category.Category) []sidebar.Group {
	var groups []sidebar.Group

	for _, root := range tree.Children {
		rootGroup := sidebar.Group{Label: root.Name.V}
		for _, l1 := range root.Children {
			rootGroup.Items = append(rootGroup.Items, sidebar.Item{
				Link:  "/client/catalog/" + l1.CategoryURL,
				Label: l1.Name.V,
				Icon:  l1.Icon.V,
			})
		}
		groups = append(groups, rootGroup)
	}

	return groups
}

func Main(c echo.Context, props MainProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"flex flex-col sm:flex-row min-h-screen min-w-[240px]\"><div id=\"hx-sidebar\" class=\"sm:w-[240px]\"><div class=\"sm:w-[240px] sm:fixed sm:inset-0 p-2 sm:overflow-y-auto\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = sidebar.Sidebar(sidebar.SidebarProps{
				Path:    c.Request().URL.Path,
				Label:   "Demo CRM / E-Commerce",
				Link:    "/client",
				Address: "@" + c.Request().Host,
				GroupsTop: []sidebar.Group{
					{
						Items: []sidebar.Item{
							{Link: "/client", Label: "Home", Icon: "fa fa-home", IsRoot: true},
						},
					},
				},
				GroupsMiddle: categoryTreeToSidebarGroups(props.CategoryTree),
				GroupsBottom: []sidebar.Group{
					{
						Label: "Project",
						Items: []sidebar.Item{
							{Link: "/", Label: "w2ui/admin demo", Icon: "fa fa-gears", IsExternal: true},
							{Link: "https://github.com/dv1x3r/gostart-crm", Label: "GitHub Project", Icon: "fa-brands fa-github", IsExternal: true},
						},
					},
				},
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div></div><main id=\"hx-main\" class=\"flex-1 flex overflow-x-auto sm:my-2 sm:mr-2 sm:rounded-lg sm:shadow-lg bg-zinc-900 p-4\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</main></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Base(c).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
